language: ruby
rvm:
  - 1.9.3
  - 1.8.7
before_script:
after_script:
script: "bundle exec rake spec"
env:
  - PUPPET_VERSION=2.7.25
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.3
notifications:
  email: false
branches:
  only:
    - master
    - /^release.*$/
